const TIPOS_AUTORIDADES = {
    PRECEPTOR: "Preceptor",
    PROFESOR: "Profesor",
    TUTOR: "Tutor",
};

const TIPOS_AUTORIDADES_ACEPTADAS = [
    TIPOS_AUTORIDADES.PRECEPTOR,
    TIPOS_AUTORIDADES.PROFESOR,
    TIPOS_AUTORIDADES.TUTOR,
];

module.exports = {
    TIPOS_AUTORIDADES,
    TIPOS_AUTORIDADES_ACEPTADAS,
};
